spring:
  h2:
    console:
      enabled: true

  mail:
    host: localhost
    port: 2525
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          auth: false

  datasource:
    url: jdbc:h2:mem:shield
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: update
    database: h2

  cloud:
    stream:
      bindings:
        output:
          destination: emails
          group: mails-group
        input:
          destination: emails
          group: mails-group



server:
  port: 9090
shield:
  jwt:
    key-store: "classpath:shield.jks"
    key-store-password: "not4public"
    key-pair-alias: "shield"
    key-pair-password: "not4public"
  app:
    activationDomainUrl: http://localhost:9090/activation

logging:
  level:
    org:
      hibernate:
        SQL: debug


  #  datasource:
  #    url: jdbc:mysql://localhost:3306/shield?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  #    username: root
#    password: passw0rd